name: NPM Registry Publisher

on:
    release:
        types: [published]
    workflow_dispatch:

jobs:
    build:
        environment:
            name: Publish to NPM Registry
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: publish
              run: npm publish --no-git-checks
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
